#!/usr/bin/python3
import argparse
from collections import Counter
parser = argparse.ArgumentParser()
parser.add_argument("corpus", type=str, help="The name of the corpus to process")
parser.add_argument("-b", "--maxbigramvocabsize", type=int, help="Specify the maximum size the vocabulary can take. Default = 40000.", default=40000)
args = parser.parse_args()


corpus = open(args.corpus+"/corpus.tok", encoding='ascii').read()
words = corpus.lower().split()

counts = Counter(w1+"_" + w2 for w1, w2 in zip(words, words[1:]))
bigramvocab = [w for w, c in counts.most_common(args.maxbigramvocabsize)]

with open(args.corpus+"/bigramvocab", "w", encoding='ascii') as vocabfile:   
  print ("\n".join(bigramvocab), file=vocabfile)

  

