#!/home/simon/MultiscaleSP/venv/bin/python3
import argparse
from sp import SP
from bytepair import bpstr

parser = argparse.ArgumentParser()
parser.add_argument("corpus", type=str, help="The name of the corpus to process.")
parser.add_argument("prefix", type=str, help="The words that provide the context for gneeration.")
parser.add_argument("-v", "--verbose", action="store_true", help="Display verbose output")
args = parser.parse_args()

s = SP(args.corpus)

EndOfUtteranceTokens = set(["_._", "_?_", "_!_"])
def truncateToks (toks):
    result = []
    for i in range(len(toks)):
        if toks[i] in EndOfUtteranceTokens:
            result.append(toks[i])
            break
        result.append(toks[i])
    return result

result = args.prefix.split()
newtoks = ["", "", "", ""]
iterations = 0
samplerStop = False
while (set(newtoks) & EndOfUtteranceTokens) == set() and iterations < 8 and not samplerStop:
    toks = s.samplerGibbs(result, BufferLength = len(result) + 3)
    if toks:
        toks = toks.split()[len(result):]
        newtoks = truncateToks(toks)
        result += newtoks
        iterations += 1
    else:
        samplerStop = True

print (bpstr(result))
     

