#!/usr/bin/python3
from sp import SP
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("corpus", type=str, help="The name of the corpus to train on")
parser.add_argument("-i", "--iterations", type=int, help="Number of optimization iterations. Default = 5.", default=5)
args = parser.parse_args()

s = SP(args.corpus)
s.learn(args.iterations)
