#!/usr/bin/python3
from sp import SP
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("corpus", type=str, help="The name of the corpus to train on")
args = parser.parse_args()

s = SP(args.corpus)
s.initParams()
s.saveParams()
