#!/usr/bin/python3
from sp import SP
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("corpus", type=str, help="The name of the corpus to train on")
parser.add_argument("-v", "--verbose", action="store_true", help="Display verbose output")
args = parser.parse_args()

s = SP(args.corpus)
s.test(args.verbose)
