#!/home/simon/MultiscaleSP/venv/bin/python3
from sp import SP
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("corpus", type=str, help="The name of the corpus to test")
parser.add_argument("-s", "--test-corpus-size", type=int, help="Number of words to test. THe first N words of the corpus will be used. By default it will use 10000 words or the size of the corpus whichever is smaller.", default=10000)
parser.add_argument('-v', '--verbose', action='store_true', help="List the words and the predicted output vectors.")
args = parser.parse_args()

s = SP(args.corpus)
s.test(size=args.test_corpus_size, verbose=args.verbose)
